import type { Note } from "./types";

export const sampleNotes: Note[] = [
  {
    id: "sample-1",
    title: "Slow mornings",
    content: "Quiet mornings make the best writing time. Try a tea ritual before notes.",
    type: "Journal",
    tags: ["ritual", "calm"],
    mood: "Calm",
    source: "Self",
    createdAt: 0,
    updatedAt: 0,
    pinned: true,
    archived: false,
    links: ["sample-2"],
  },
  {
    id: "sample-2",
    title: "Idea: Local-first studio",
    content: "Build a tiny personal studio where everything is saved locally and synced only when needed.",
    type: "Idea",
    tags: ["local-first", "product"],
    mood: "Focused",
    source: "Notebook",
    createdAt: 0,
    updatedAt: 0,
    pinned: false,
    archived: false,
    links: ["sample-3"],
  },
  {
    id: "sample-3",
    title: "Quote: Sontag",
    content: "\"A writer is someone who pays attention to the world.\"",
    type: "Quote",
    tags: ["writing"],
    mood: "Calm",
    source: "Reading list",
    createdAt: 0,
    updatedAt: 0,
    pinned: false,
    archived: false,
    links: [],
  },
  {
    id: "sample-4",
    title: "Observation: cues",
    content: "Noticing how micro cues change focus. A gentle chime resets attention without friction.",
    type: "Observation",
    tags: ["focus"],
    mood: "Focused",
    source: "Today",
    createdAt: 0,
    updatedAt: 0,
    pinned: false,
    archived: false,
    links: ["sample-2"],
  },
];
